-- seed.sql
-- Starter data for FitShare / open workout database.
-- Run this after schema.sql.

USE fitshare_db;

INSERT INTO workout_goals (name, slug, description) VALUES
('Strength', 'strength', 'Training focused on increasing muscular strength.'),
('Hypertrophy', 'hypertrophy', 'Training focused on muscle growth.'),
('Endurance', 'endurance', 'Training focused on stamina and repeated effort.'),
('Weight Loss', 'weight-loss', 'Training focused on calorie expenditure and fat loss.'),
('Mobility', 'mobility', 'Training focused on flexibility and range of motion.'),
('General Fitness', 'general-fitness', 'Training focused on overall health and conditioning.');

INSERT INTO categories (name, slug, description) VALUES
('Full Body', 'full-body', 'Workouts that train the whole body.'),
('Upper Body', 'upper-body', 'Workouts focused on upper body muscles.'),
('Lower Body', 'lower-body', 'Workouts focused on legs and glutes.'),
('Core', 'core', 'Workouts focused on abdominal and trunk muscles.'),
('Cardio', 'cardio', 'Workouts focused on cardiovascular fitness.'),
('Mobility', 'mobility', 'Workouts focused on flexibility and mobility.'),
('Home Workout', 'home-workout', 'Workouts that can be done at home.'),
('Gym Workout', 'gym-workout', 'Workouts designed for gym equipment.');

INSERT INTO exercises (name, slug, description, muscle_group, equipment, difficulty) VALUES
('Push-up', 'push-up', 'Bodyweight exercise for chest, shoulders, and triceps.', 'Chest', 'Bodyweight', 'beginner'),
('Squat', 'squat', 'Lower body exercise focused on quads, glutes, and hamstrings.', 'Legs', 'Bodyweight', 'beginner'),
('Plank', 'plank', 'Static core exercise focused on trunk stability.', 'Core', 'Bodyweight', 'beginner'),
('Pull-up', 'pull-up', 'Upper body pulling exercise for back and biceps.', 'Back', 'Pull-up bar', 'intermediate'),
('Bench Press', 'bench-press', 'Chest-focused pressing exercise using a barbell.', 'Chest', 'Barbell', 'intermediate'),
('Deadlift', 'deadlift', 'Compound movement for posterior chain strength.', 'Back/Legs', 'Barbell', 'advanced'),
('Lunge', 'lunge', 'Single-leg lower body exercise.', 'Legs', 'Bodyweight', 'beginner'),
('Shoulder Press', 'shoulder-press', 'Overhead pressing exercise for shoulders and triceps.', 'Shoulders', 'Dumbbells or barbell', 'intermediate'),
('Bicep Curl', 'bicep-curl', 'Isolation exercise for the biceps.', 'Arms', 'Dumbbells', 'beginner'),
('Jumping Jacks', 'jumping-jacks', 'Simple cardio exercise using bodyweight.', 'Full Body', 'Bodyweight', 'beginner');

INSERT INTO hashtags (tag) VALUES
('beginner'),
('strength'),
('homeworkout'),
('gym'),
('legday'),
('pushday'),
('cardio'),
('mobility'),
('bodyweight'),
('fitness');

-- Optional demo user.
-- Replace the password_hash value with a real bcrypt hash generated by your Node app.
INSERT INTO users (username, email, password_hash, role) VALUES
('demo_user', 'demo@example.com', 'REPLACE_WITH_REAL_BCRYPT_HASH', 'user');

INSERT INTO profiles (user_id, display_name, bio, fitness_level) VALUES
(1, 'Demo User', 'Example profile for testing the workout feed.', 'beginner');

-- Optional demo workout post.
INSERT INTO workout_posts (
  user_id,
  goal_id,
  category_id,
  title,
  slug,
  caption,
  image_url,
  total_duration_minutes,
  rest_between_exercises_seconds,
  visibility
) VALUES (
  1,
  1,
  2,
  'Beginner Push Day',
  'beginner-push-day',
  'Simple beginner upper body workout with bodyweight exercises.',
  NULL,
  30,
  120,
  'public'
);

INSERT INTO workout_post_exercises (
  post_id,
  exercise_id,
  exercise_order,
  set_count,
  reps,
  time_seconds,
  rest_between_sets_seconds,
  rest_after_exercise_seconds,
  notes
) VALUES
(1, 1, 1, 3, 12, NULL, 60, 120, 'Keep your body straight.'),
(1, 3, 2, 3, NULL, 45, 60, 120, 'Hold a stable plank position.'),
(1, 10, 3, 3, 30, NULL, 45, NULL, 'Use as a light finisher.');

INSERT INTO workout_post_hashtags (post_id, hashtag_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 9);
